github actions : build UI => copy dist to VPS => update docker-compose.yml => relunch docker compose

diff --git a/.github/workflows/CI-image-client.yml b/.github/workflows/CI-image-client.yml
--- a/.github/workflows/CI-image-client.yml
+++ b/.github/workflows/CI-image-client.yml
@@ -16,37 +16,45 @@ jobs:
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
-          node-version: '18'
+          node-version: '20.12.2'
 
       - name: Install dependencies
         run: npm ci
 
       - name: Build the Vite project
         run: |
-          VITE_URL_SPHERUS_API=https://spherus.luc-dev.com npm run build
+          VITE_URL_SPHERUS_API=https://staging.spherus.luc-dev.com npm run build
 
-
-      - name: Deploy to VPS via SSH
-        uses: appleboy/ssh-action@v0.1.7
+      - name: Copy dist build files to VPS
+        uses: appleboy/scp-action@v0.1.7
         with:
-          host: ${{ secrets.VPS_HOST }}
-          username: ${{ secrets.VPS_USER }}
-          key: ${{ secrets.VPS_SSH_KEY }}
-          port: ${{ secrets.VPS_PORT }}
+          host: ${{ secrets.HOST }}
+          username: ${{ secrets.USERNAME }}
+          password: ${{ secrets.PASSWORD }}
+          port: ${{ secrets.PORT }}
+          source: "dist/*"
+          target: /home/lukasz/apps/spherus/staging/client/${{ github.ref_name }}/
+          strip_components: 1
+
+      - name: Update NGINX volume inside docker-compose.stagig.yml 
+        uses: appleboy/ssh-action@v1.1.0
+        with:
+          host: ${{ secrets.HOST }}
+          username: ${{ secrets.USERNAME }}
+          password: ${{ secrets.PASSWORD }}
+          port: ${{ secrets.PORT }}
           script: |
             VERSION=${{ github.ref_name }}
-            DEPLOY_PATH="/home/lukasz/apps/spherus/staging/client"
-            
-            # Create the versioned directory
-            mkdir -p $DEPLOY_PATH/$VERSION
-            
-            # Transfer the built dist files to the versioned directory
-            # scp -r dist/* ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:$DEPLOY_PATH/$VERSION
-            rsync -avz -e "ssh -p ${{ secrets.VPS_PORT }}" dist/ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/$DEPLOY_PATH/$VERSION
-            
-            # Update NGINX config to point to the new version
-            sed -i "s|$DEPLOY_PATH/v[^/]*|$DEPLOY_PATH/$VERSION|" /home/lukasz/apps/spherus/staging/docker-compose.prod.yml
+            STAGING_PATH="/home/lukasz/apps/spherus/staging"
+            CLIENT_PATH="$STAGING_PATH/client"
+            DEPLOY_PATH="$CLIENT_PATH/$VERSION"
 
+            # Update docker-compose.staging.yml to point to the new volume for nginx
+            sed -i "s|$CLIENT_PATH/v[^/]*|$DEPLOY_PATH:|" $STAGING_PATH/docker-compose.staging.yml || { echo "Failed to change docker-compose.staging.yml"; exit 1; }
+            
             # Restart NGINX to apply the new configuration
-            docker compose -f docker-compose.prod.yml down &&
-            docker compose -f docker-compose.prod.yml up --build -d
+            cd $STAGING_PATH
+            docker compose -f docker-compose.staging.yml down --volumes &&
+            docker compose -f docker-compose.staging.yml up --build -d
+
+            echo "Deployment completed."
